import Base
import ../laws/Db.bend as Laws

def Laws.db_ryw():
  {==}

def Laws.db_del():
  {==}

def Laws.db_batch_atomic():
  {==}

def Laws.db_recover():
  {==}

def Laws.db_get_newest_wins():
  {==}

def Laws.db_get_tombstone_hides():
  {==}

def Laws.db_get_miss():
  {==}

def Laws.db_cache_transparent_hit():
  {==}

def Laws.db_cache_transparent_tomb():
  {==}

def Laws.db_cache_transparent_miss():
  {==}
